train:
  device: cuda:1
  pretrain_model: ./save/fire_window25_np_norm100.pth #./save/backbone_unet.pth    # None or a pth file
  model_save_prefix: flori_win31_3 #./save/SuperRetina.pth
  model_image_width: 1456
  model_image_height: 1456
  data_aug_type: 3 # 1:灰度图 2:绿色通道 3:其余的方法
  big_resolution: True
  image_original_size: 2912 #和关键点的坐标系的尺寸相关
  train_fire_dir: /home/yepeng_liu/code_base/unet_pretrain/displacement_train_retinal/train_datas/flori_data/sift_seg_align/align_img/
  anno_file_dir: /home/yepeng_liu/code_base/unet_pretrain/displacement_train_retinal/train_datas/flori_data/sift_seg_align/align_anno/
  save_files_dir: ./save/
  use_matching_trick: True
  use_guide_map: False
  use_score_map: False
  nms_size: 10
  nms_thresh: 0.01
  knn_thresh: 0.9
  keypoint_number: 14
  train_epochs: 800
  ir_epochs: [500, 700]
  save_epochs: 100
  batch_size: 4
  loss: ncc # loss function ： l1.l2,ncc
  window_size: 31 # default: 9
  lr: 0.001 # ncc,0.0005
  loss_with_smooth: True
  loss_weights: [1,1,0.0000001,0.2] # mse,smooth,keypoints [1,1,0.1]
  train_with_kp: True
PREDICT:
  device: cuda:1
  model_save_path: ./save/fire_window25200.pth #./save/SuperRetina.pth
  pretrain_model: None   # None or a pth file
  model_image_width: 1456
  model_image_height: 1456
  test_method: 2 # 1代表测试两张图片，2代表测试fire文件夹内所有的匹配对，3代表将变换后的两幅图像融合在一起
  # test_fire_dir: /home/yepeng_liu/code_base/unet_pretrain/displacement_train_retinal/train_datas/flori_data/val_10_9/align_img/
  # test_gt_dir: /home/yepeng_liu/code_base/unet_pretrain/displacement_train_retinal/train_datas/flori_data/val_10_9/align_gt/
  test_fire_dir: /home/yepeng_liu/code_base/unet_pretrain/displacement_train_retinal/train_datas/flori_data/sift_seg_align/align_img/
  test_gt_dir: /home/yepeng_liu/code_base/unet_pretrain/displacement_train_retinal/train_datas/flori_data/sift_seg_align/align_anno/
  save_files_dir: ./visulize_files/
  use_matching_trick: True
  nms_size: 10
  nms_thresh: 0.01
  knn_thresh: 0.9
  is_gray: True
  image_single_channel: True
  image_original_size: 2912 #和关键点的坐标系的尺寸相关